src/main/java/lt/vtvpmc/exam/entities/Client.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Client implements Serializable {

	private static final long serialVersionUID = -4082230778255953111L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long id;

	private String firstName;

	private String lastName;

	private String phoneNumber;

	@Temporal(TemporalType.DATE)
	private Date birthDate;

	private Boolean isLoyal;

	@OneToMany(mappedBy = "client", orphanRemoval = true, fetch = FetchType.EAGER)
	private List<Inventory> inventories;

	public Client() {
	}

	public Client(String firstName, String lastName, String phoneNumber) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Boolean getIsLoyal() {
		return isLoyal;
	}

	public void setIsLoyal(Boolean isLoyal) {
		this.isLoyal = isLoyal;
	}

	public List<Inventory> getInventories() {
		return inventories;
	}

	public void setInventories(List<Inventory> inventories) {
		this.inventories = inventories;
	}

}

src/main/java/lt/vtvpmc/exam/entities/Inventory.java
package lt.vtvpmc.exam.entities;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lt.vtvpmc.exam.entities.Client;

@Entity
public class Inventory {

	@Id
	@GeneratedValue
	private Long id;

	private String name;

	private Double weight;

	private Integer sector;

	@Temporal(TemporalType.DATE)
	private Date entryDate;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "client_id")
	private Client client;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getWeight() {
		return weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public Integer getSector() {
		return sector;
	}

	public void setSector(Integer sector) {
		this.sector = sector;
	}

	public Date getEntryDate() {
		return entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
}

src/main/java/lt/vtvpmc/exam/entities/repositories/ClientRepository.java
package lt.vtvpmc.exam.entities.repositories;

import java.util.List;

import lt.vtvpmc.exam.entities.Client;

public interface ClientRepository {

	void save(Client newClient);

	void delete(Client client);

	List<Client> findAll();

	Client findById(Long id);

	Long countClients();

	List<Client> findTop5ByWeight();

	List<Client> findTop5ByUnits();

}

src/main/java/lt/vtvpmc/exam/entities/repositories/InventoryRepository.java
package lt.vtvpmc.exam.entities.repositories;

import java.util.List;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Inventory;

public interface InventoryRepository {

	public void save(Inventory inventory);

	public void delete(Inventory inventory);

	public List<Inventory> findAll();

	public List<Inventory> findAllByClient(Client client);

	public Long countEntriesByClient(Client client);

}

src/main/java/lt/vtvpmc/exam/entities/repositories/jpa/ClientRepositoryJPA.java
package lt.vtvpmc.exam.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.repositories.ClientRepository;

public class ClientRepositoryJPA implements ClientRepository {

	static final Logger log = LoggerFactory.getLogger(ClientRepositoryJPA.class);

	private EntityManagerFactory entityManagerFactory;

	public void setEntityManagerFactory(EntityManagerFactory emf) {
		this.entityManagerFactory = emf;
	}

	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}

	@Override
	public void save(Client client) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			if (!entityManager.contains(client))
				client = entityManager.merge(client);
			entityManager.persist(client);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public void delete(Client client) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			client = entityManager.merge(client);
			entityManager.remove(client);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public List<Client> findAll() {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Client> cq = cb.createQuery(Client.class);
			Root<Client> root = cq.from(Client.class);
			cq.select(root);
			TypedQuery<Client> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public Long countClients() {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Long> cq = cb.createQuery(Long.class);
			Root<Client> root = cq.from(Client.class);
			cq.select(cb.count(root));
			TypedQuery<Long> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public Client findById(Long id) {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Client> cq = cb.createQuery(Client.class);
			Root<Client> root = cq.from(Client.class);
			cq.where(cb.equal(root.get("id"), id));
			TypedQuery<Client> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}

	public List<Client> findTop5ByWeight() {
		return null;
	}

	public List<Client> findTop5ByUnits() {
		return null;
	}

}

src/main/java/lt/vtvpmc/exam/entities/repositories/jpa/InventoryRepositoryJPA.java
package lt.vtvpmc.exam.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Inventory;
import lt.vtvpmc.exam.entities.repositories.InventoryRepository;

public class InventoryRepositoryJPA implements InventoryRepository {

	private EntityManagerFactory entityManagerFactory;

	public void setEntityManagerFactory(EntityManagerFactory emf) {
		this.entityManagerFactory = emf;
	}

	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}

	@Override
	public void save(Inventory inventory) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			if (!entityManager.contains(inventory) && inventory.getId() != null) {
				inventory = entityManager.merge(inventory);
			}
			entityManager.persist(inventory);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public void delete(Inventory inventory) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			inventory = entityManager.merge(inventory);
			entityManager.remove(inventory);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public List<Inventory> findAll() {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Inventory> cq = cb.createQuery(Inventory.class);
			Root<Inventory> root = cq.from(Inventory.class);
			cq.select(root);
			TypedQuery<Inventory> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public List<Inventory> findAllByClient(Client client) {
		EntityManager entityManager = getEntityManager();
		try {
			client = entityManager.merge(client);
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Inventory> cq = cb.createQuery(Inventory.class);
			Root<Inventory> root = cq.from(Inventory.class);
			cq.select(root);
			cq.where(cb.equal(root.get("client"), client));
			TypedQuery<Inventory> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public Long countEntriesByClient(Client client) {
		EntityManager entityManager = getEntityManager();
		try {
			client = entityManager.merge(client);
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Long> cq = cb.createQuery(Long.class);
			Root<Inventory> root = cq.from(Inventory.class);
			cq.select(cb.count(root));
			cq.where(cb.equal(root.get("client"), client));
			TypedQuery<Long> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}

}

src/main/java/lt/vtvpmc/exam/ui/models/ClientModel.java
package lt.vtvpmc.exam.ui.models;

import lt.vtvpmc.exam.entities.Client;

import java.io.Serializable;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ClientModel implements Serializable {

	private static final long serialVersionUID = 5040310448257955354L;

	static final Logger log = LoggerFactory.getLogger(ClientModel.class);

	@Valid
	private Client currentClient;

	public void init() {
		currentClient = new Client();
	}

	public Client getCurrentClient() {
		return currentClient;
	}

	public void setCurrentClient(Client currentClient) {
		this.currentClient = currentClient;
	}

}

src/main/java/lt/vtvpmc/exam/ui/models/InventoryModel.java
package lt.vtvpmc.exam.ui.models;

import java.io.Serializable;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.vtvpmc.exam.entities.Inventory;

public class InventoryModel implements Serializable {

	private static final long serialVersionUID = -4516264053477353885L;

	static final Logger log = LoggerFactory.getLogger(InventoryModel.class);

	@Valid
	private Inventory currentInventory;

	public void init() {
		currentInventory = new Inventory();
	}

	public Inventory getCurrentInventory() {
		return currentInventory;
	}

	public void setCurrentInventory(Inventory currentInventory) {
		this.currentInventory = currentInventory;
	}

}

src/main/java/lt/vtvpmc/exam/ui/controllers/ClientController.java
package lt.vtvpmc.exam.ui.controllers;

import java.io.Serializable;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.services.ClientService;
import lt.vtvpmc.exam.ui.models.ClientModel;

public class ClientController implements Serializable {

	private static final long serialVersionUID = 8760837696654598218L;

	static final Logger log = LoggerFactory.getLogger(ClientController.class);

	public static final String NAV_LIST_CLIENTS = "list-clients";
	public static final String NAV_LIST_INVENTORY = "list-inventory";

	private ClientModel clientModel;
	private ClientService clientService;

	public void create() {
		clientModel.setCurrentClient(new Client());
	}

	public String delete(Client client) {
		clientService.delete(client);
		return NAV_LIST_CLIENTS;
	}

	public List<Client> getClientList() {
		return clientService.findAll();
	}

	public String update(Client client) {
		clientModel.setCurrentClient(client);
		return NAV_LIST_INVENTORY;
	}

	public String save() {
		clientService.save(clientModel.getCurrentClient());
		return NAV_LIST_CLIENTS;
	}

	public String cancel() {
		clientModel.setCurrentClient(new Client());
		return NAV_LIST_CLIENTS;
	}

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}

	public ClientService getClientService() {
		return clientService;
	}

	public void setClientService(ClientService clientService) {
		this.clientService = clientService;
	}

}

src/main/java/lt/vtvpmc/exam/ui/controllers/InventoryController.java
package lt.vtvpmc.exam.ui.controllers;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Inventory;
import lt.vtvpmc.exam.services.InventoryService;
import lt.vtvpmc.exam.ui.models.ClientModel;
import lt.vtvpmc.exam.ui.models.InventoryModel;

public class InventoryController implements Serializable {

	private static final long serialVersionUID = -6091679281444163424L;

	private ClientModel clientModel;
	private InventoryModel inventoryModel;
	private InventoryService inventoryService;

	public void create() {
		inventoryModel.setCurrentInventory(new Inventory());
	}

	public void update(Inventory inventory) {
		inventoryModel.setCurrentInventory(inventory);
	}

	public String save() {
		inventoryModel.getCurrentInventory().setClient(clientModel.getCurrentClient());
		inventoryModel.getCurrentInventory().setEntryDate(new Date());
		inventoryService.save(inventoryModel.getCurrentInventory());
		inventoryModel.setCurrentInventory(new Inventory());
		return ClientController.NAV_LIST_INVENTORY;
	}

	public String delete(Inventory inventory) {
		inventoryService.delete(inventory);
		return ClientController.NAV_LIST_INVENTORY;
	}

	public String cancel() {
		inventoryModel.setCurrentInventory(new Inventory());
		return ClientController.NAV_LIST_INVENTORY;
	}

	public List<Inventory> findAllByCurrentClient() {
		if (clientModel.getCurrentClient() == null)
			return null;
		return inventoryService.findAllByClient(clientModel.getCurrentClient());
	}

	public Long countEntries(Client client) {
		return inventoryService.countEntriesByClient(client);
	}

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}

	public InventoryModel getInventoryModel() {
		return inventoryModel;
	}

	public void setInventoryModel(InventoryModel inventoryModel) {
		this.inventoryModel = inventoryModel;
	}

	public InventoryService getInventoryService() {
		return inventoryService;
	}

	public void setInventoryService(InventoryService inventoryService) {
		this.inventoryService = inventoryService;
	}

}

src/main/java/lt/vtvpmc/exam/ui/controllers/ReportsController.java
package lt.vtvpmc.exam.ui.controllers;

import java.io.Serializable;
import java.util.List;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.services.ReportsService;

public class ReportsController implements Serializable {

	private static final long serialVersionUID = 5989889322482017778L;

	private ReportsService reportsService;

	public List<Client> reportTop5ClientsByWeight() {
		return reportsService.findTop5ClientsByWeight();
	}

	public List<Client> reportTop5ClientsByUnits() {
		return reportsService.findTop5ClientsByUnits();
	}

	public void reportTop5SectorsByWeight() {

	}

	public void reportTop5SectorsByUnits() {

	}

	public ReportsService getReportsService() {
		return reportsService;
	}

	public void setReportsService(ReportsService reportsService) {
		this.reportsService = reportsService;
	}

}

src/main/webapp/clients.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="content">
		<h:form id="dataTable">
			<p:dataTable value="#{clientController.clientList}" var="client">
				<f:facet name="header">All Clients</f:facet>
				<p:column headerText="Name">
					<h:outputText value="#{client.firstName}" />
				</p:column>
				<p:column headerText="Surname">
					<h:outputText value="#{client.lastName}" />
				</p:column>
				<p:column headerText="Birth Date">
					<h:outputText value="#{client.birthDate}" />
				</p:column>
				<p:column headerText="Phone">
					<h:outputText value="#{client.phoneNumber}" />
				</p:column>
				<p:column headerText="Loyal client">
					<h:outputText value="#{client.isLoyal}" />
				</p:column>
				<p:column headerText="Inventory entries">
					<h:outputText value="#{inventoryController.countEntries(client)}" />
				</p:column>
				<p:column headerText="">
					<p:commandButton value="Open"
						action="#{clientController.update(client)}">
					</p:commandButton>
				</p:column>
				<p:column headerText="">
					<p:commandButton value="Delete"
						action="#{clientController.delete(client)}">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert" />
					</p:commandButton>
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Yes" type="button"
							styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:column>
			</p:dataTable>
		</h:form>
		<p:commandButton action="#{clientController.create}"
			update="updateForm" value="Create client"
			oncomplete="PF('createClient').show();" />
		<p:dialog header="Create Client" widgetVar="createClient" modal="true"
			showEffect="fade" hideEffect="fade" resizable="false">
			<h:form id="updateForm">
				<p:outputPanel rendered="#{clientModel.currentClient != null}">
					<h:panelGrid columns="3" cellpadding="5">
						<p:outputLabel for="name">Name:</p:outputLabel>
						<p:inputText id="name"
							value="#{clientController.clientModel.currentClient.firstName}"
							required="true">
							<f:validateLength minimum="2" maximum="20" />
						</p:inputText>
						<p:message for="name"></p:message>

						<p:outputLabel for="surname">Surname:</p:outputLabel>
						<p:inputText id="surname"
							value="#{clientController.clientModel.currentClient.lastName}"
							required="true">
							<f:validateLength minimum="2" maximum="20" />
						</p:inputText>
						<p:message for="surname"></p:message>

						<p:outputLabel for="birthDate">Date of birth:</p:outputLabel>
						<p:calendar id="birthDate"
							value="#{clientController.clientModel.currentClient.birthDate}">
						</p:calendar>
						<p:message for="birthDate"></p:message>

						<p:outputLabel for="phone">Phone:</p:outputLabel>
						<p:inputText id="phone"
							value="#{clientController.clientModel.currentClient.phoneNumber}">
							<f:convertNumber integerOnly="true" />
						</p:inputText>
						<p:message for="phone"></p:message>

						<p:outputLabel for="loyal">Loyal:</p:outputLabel>
						<h:selectOneMenu id="loyal"
							value="#{clientController.clientModel.currentClient.isLoyal}">
							<f:selectItem itemValue="#{null}" itemLabel="Not selected" />
							<f:selectItem itemValue="true" itemLabel="Loyal" />
							<f:selectItem itemValue="false" itemLabel="Normal" />
						</h:selectOneMenu>
						<p:message for="loyal"></p:message>

						<p:commandButton value="Save"
							actionListener="#{clientController.save}"
							update="updateForm dataTable"
							oncomplete="if (!args.validationFailed) PF('createClient').hide();">
						</p:commandButton>
						<p:commandButton value="Cancel"
							actionListener="#{clientController.cancel}"
							update="updateForm dataTable"
							oncomplete="PF('createClient').hide();" immediate="true">
						</p:commandButton>
					</h:panelGrid>
				</p:outputPanel>
			</h:form>
		</p:dialog>
	</ui:define>

	<ui:define name="title">
          All clients
    </ui:define>

</ui:composition>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Warehouse: <ui:insert name="title">
            No title
        </ui:insert>
	</title>
	<h:outputStylesheet name="styles.css"></h:outputStylesheet>
</h:head>
<h:body>
	<div id="container">
		<div id="menu">
			<h:form>
				<p:tabMenu activeIndex="#{param.i}">
					<p:menuitem value="Clients" outcome="list-clients"
						icon="ui-icon-person">
						<f:param name="i" value="0" />
					</p:menuitem>
					<p:menuitem value="Reports" outcome="list-reports"
						icon="ui-icon-folder-open">
						<f:param name="i" value="1" />
					</p:menuitem>
				</p:tabMenu>
			</h:form>
		</div>
		<div id="layout">
			<div id="leftside">
				<ui:insert name="leftside" />
			</div>
			<div id="rightside">
				<ui:insert name="rightside" />
			</div>
		</div>
		<div id="contents">
			<ui:insert name="content" />
		</div>
	</div>
</h:body>
</html>

src/main/webapp/reports.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="title">
        Warehouse reports
    </ui:define>
	<ui:define name="content">
		<p:panelGrid columns="1" cellpadding="5">
			<f:facet name="header">All Reports</f:facet>
			<p:commandButton value="Top 5 CLIENTS by warehoused weight"
				oncomplete="PF('clientsByWeight').show();" />
			<p:commandButton
				action="#{reportsController.reportTop5ClientsByUnits}"
				value="Top 5 CLIENTS by inventory units"
				oncomplete="PF('clientsByUnits').show();" />
			<p:commandButton
				action="#{reportsController.reportTop5SectorsByWeight}"
				value="Top 5 SECTORS by warehoused weight"
				oncomplete="PF('sectorsByWeight').show();" />
			<p:commandButton
				action="#{reportsController.reportTop5SectorsByUnits}"
				value="Top 5 SECTORS by inventory units"
				oncomplete="PF('sectorsByUnits').show();" />
		</p:panelGrid>

		<p:dialog header="Top 5 clients by weight" widgetVar="clientsByWeight"
			modal="true" showEffect="fade" hideEffect="fade" resizable="false">
			<p:dataTable value="#{reportsController.reportTop5ClientsByWeight()}"
				var="client">
				<p:column headerText="Name">
					<h:outputText value="#{client.firstName}" />
				</p:column>
			</p:dataTable>
			<p:commandButton value="Exit"
				oncomplete="PF('clientsByWeight').hide();" immediate="true">
			</p:commandButton>
		</p:dialog>
		<p:dialog header="Top 5 clients by units" widgetVar="clientsByUnits"
			modal="true" showEffect="fade" hideEffect="fade" resizable="false">
			<p:dataTable value="#{reportsController.reportTop5ClientsByUnits()}"
				var="client">
				<p:column headerText="Name">
					<h:outputText value="#{client.firstName}" />
				</p:column>
			</p:dataTable>
			<p:commandButton value="Exit"
				oncomplete="PF('clientsByUnits').hide();" immediate="true">
			</p:commandButton>
		</p:dialog>
		<p:dialog header="Top 5 sectors by weight" widgetVar="sectorsByWeight"
			modal="true" showEffect="fade" hideEffect="fade" resizable="false">
			<p:commandButton value="Exit"
				oncomplete="PF('sectorsByWeight').hide();" immediate="true">
			</p:commandButton>
		</p:dialog>
		<p:dialog header="Top 5 sectors by units" widgetVar="sectorsByUnits"
			modal="true" showEffect="fade" hideEffect="fade" resizable="false">
			<p:commandButton value="Exit"
				oncomplete="PF('sectorsByUnits').hide();" immediate="true">
			</p:commandButton>
		</p:dialog>
	</ui:define>
</ui:composition>